# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")  # App Store 배포용 프로비저닝 파일 다운로드
    increment_build_number(xcodeproj: "Musical-Notes.xcodeproj")  # 빌드 번호 증가
    gym(scheme: "Musical-Notes")  # 빌드 생성
    pilot(upload: true)  # TestFlight에 업로드
  end
end
