# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: pull_request_on_develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Xcode version 15.3
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
    - name: Install Provisioning Profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/${{ secrets.PROVISION }}.mobileprovision
    - name: Build
      run: xcodebuild clean build -project ./Musical-Notes.xcodeproj -scheme Musical-Notes -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=16.0'
