# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: pull_request_on_develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Xcode version 15.3
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
      
    - name: Set up GoogleService-Info.plist
      run: |
        mkdir -p Musical-Notes/Musical-Notes
        echo "${{ secrets.GOOGLESERVICE_INFO }}" | base64 --decode > Musical-Notes/Musical-Notes/GoogleService-Info.plist
        
    - name: Ensure GoogleService-Info.plist is in the correct directory
      run: |
        mkdir -p Musical-Notes/Musical-Notes/Musical-Notes
        mv Musical-Notes/Musical-Notes/GoogleService-Info.plist Musical-Notes/Musical-Notes/Musical-Notes/GoogleService-Info.plist
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        
    - name: Set up Git authentication
      run: |
        git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com".insteadOf "https://github.com"
        
    - name: Fetch provisioning profiles using match
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        bundle exec fastlane match development --type development --readonly
        
    - name: Build
      run: xcodebuild clean build -project ./Musical-Notes.xcodeproj -scheme Musical-Notes -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=16.0'
